### PR TITLE
TMA & YAML v1.2

### PR DESCRIPTION
**Pull request by bioinfonerd**
Update for TMA & YAML parsingV1.2 which includes:

        - Added TMA functionality and executed as passing argument
        - Added pipeline will not re-run if parts of pipeline already run (ie if ashlar stitched present, start from there)
        - Added more code comments
        - Updated user documentation to reflect new additions and to include feedback from non-computer science users
        - Added User passed parameters using YAML file
        - Added environment and module version tracking
        - Added ability to update if new versions from developers
        - Added ability to use ashlar version cf25 for older images
        - Added varying QC checks to pipeline
                - Check if user correctly formatted folder structure
                - Check if user modified raw cycle names and warn if they have
                - Add ability to switch between RareCyte and Exemplar Data
        - Added summary file of what parts of pipeline progress for each image
        - Added storing run log files into separate folder based on yaml run name (if same name, appends time stamp)

### CODE REVIEW

**Comment by ArtemSokolov** [comment]
Some comments / suggestions:

1. Rebase the branch to feba154 and resolve conflicts (if any still remain after rebasing).
2. Consider moving version information into a standalone file (traditionally called some variant of `CHANGES`) so it doesn't clog up README.
3. Since this will become the new "master" version, consider placing its instantiation back into `/n/groups/lsp/cycif/cycif_pipeline` and updating `bin/cycif_pipeline_activate.sh` accordingly.
4. We discussed preventing illumination profiles from being removed by `clean.sh` (as per #25). Let's comment out `rm -fr */illumination_profiles` for now. Eventually, we will probably want a more robust solution.
5. Minor point of style: since git already does version control for you, consider avoiding explicit version numbers in filenames (e.g., `bin/transfer_v1.2.sbatch`). It creates additional spots to maintain by hand, which may go stale or become confusing over time.

**Comment by bioinfonerd** [comment]
Not sure where Artem's comments and suggestions went, but I resolved them.

**Comment by ArtemSokolov** [comment]
Thanks, Nathan. Something's wrong with your `run_batchUNet2DtCycif_mcmicro.py`. It looks like git conflicts got baked directly into the file.

Everything else looks good.

**Comment by bioinfonerd** [comment]
Wonderful, I resolved the git conflict changes, so should be good now

**Pull request merged**
